
'BETACAD
Private Sub ExpBetaCAD_Click()

    Dim LAYER As AcadLayer
    Dim SHEETNUM
    Dim CONCAT
    Dim FILENAME
    Dim NAMELEN
    
    ThisDrawing.Save
    'ThisDrawing.SendCommand ("-Layer ")
    'ThisDrawing.SendCommand ("m ")
    'ThisDrawing.SendCommand ("0")
    'ThisDrawing.SendCommand (vbCr)
    'ThisDrawing.SendCommand ("off ")
    'ThisDrawing.SendCommand ("foglio*")
    'ThisDrawing.SendCommand (vbCr)
    'ThisDrawing.SendCommand ("_fre ")
    'ThisDrawing.SendCommand ("foglio*")
    'ThisDrawing.SendCommand (vbCr)
    'ThisDrawing.SendCommand ("_t ")
    'ThisDrawing.SendCommand ("0")
    'ThisDrawing.SendCommand (vbCr)
    'ThisDrawing.SendCommand ("m ")
    'ThisDrawing.SendCommand ("0")
    'ThisDrawing.SendCommand (vbCr)
    'ThisDrawing.SendCommand (vbCr)
    
    For Each LAYER In ThisDrawing.Layers
        SHEETNUM = Mid(LAYER.NAME, 7, 3)
        If IsNumeric(SHEETNUM) Then
            If SHEETNUM < 0 Then SHEETNUM = SHEETNUM * -1
            CONCAT = "000" & SHEETNUM
            LAYER.NAME = "F" & Right(CONCAT, 3) & "-DISEGNO"
            ThisDrawing.Layers.Add "F" & Right(CONCAT, 3) & "-BASI"
            ThisDrawing.Layers.Add "F" & Right(CONCAT, 3) & "-REVI"
        End If
    Next
    
    NAMELEN = Len(ThisDrawing.NAME) - 4
    FILENAME = Mid(ThisDrawing.NAME, 1, Int(NAMELEN))
    ThisDrawing.SaveAs ThisDrawing.Path & "\" & FILENAME + " - BETACAD.dwg"
    MsgBox "Conversione Terminata", vbInformation

End Sub